FROM nvidia/cuda:11.6.0-devel-ubuntu20.04

RUN apt update && apt install python3-pip wget -y

RUN pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.251/quarto-1.1.251-linux-amd64.deb 

RUN dpkg -i quarto-1.1.251-linux-amd64.deb  